#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "$0 <directory>"
  exit 1
fi

DIR="$1"

if [ ! -d "$DIR" ]; then
  echo "'$DIR' is not real"
  exit 1
fi

shopt -s nullglob nocaseglob
for file in "$DIR"/*.{png,jpg,jpeg,webp,bmp,tiff,gif}; do
  [ -e "$file" ] || continue

  echo "$(basename "$file")"

  tmpfile="${file}.tmp"

  convert "$file" -strip "$tmpfile"

  if [ -f "$tmpfile" ]; then
    mv -f "$tmpfile" "$file"
  else
    echo "failed for $file"
  fi
done
